POPULATION_SIZE = 100
MUTATION_RATE = 0.3
DEFAULT_GENERATIONS = 50
MAX_COMPONENTS = 4
MIN_CIRCUIT_LENGTH = 1
MAX_CIRCUIT_LENGTH = 5
KEY_CIRCUIT = "circuit"

ALLOWED_COMPONENTS = [
    "BS",
    "HWP(45)",
    "QWP(45)",
    "PHASE(90)",
    "ID"
]
